tools:
    external_code_coverage: true
    php_cpd: false
    php_pdepend:
        enabled: true
        filter:
            paths: ["src/app/*"]
    js_hint: false
    php_code_sniffer:
        extensions:
            - php
        command: phpcs
        enabled: true
        filter:
            paths: ["src/app/*"]
        config:
          ruleset: rulesets/phpcs.xml
    php_mess_detector:
        enabled: true
        config:
           # ruleset: rulesets/phpmd-ruleset.xml
            design_rules: { eval_expression: false }
        filter:
            paths: ["src/app/*"]

    php_loc:
        enabled: true
        excluded_dirs: ["src/app/*"]
#    php_analyzer: true # cannot use as composer dependencies can't be found

