language: php

env:
  - DB=mysql

php:
  - 5.3

before_script:
  - git clone https://github.com/andrewkett/magento-mirror.git web
  - mkdir web/.modman
  - mkdir web/.modman/Ak_Locator
  - rsync -av --progress ./ ./web/.modman/Ak_Locator --exclude web
  - cd web
  - wget https://raw.githubusercontent.com/colinmollenhour/modman/master/modman
  - chmod +x ./modman
  - ./modman deploy Ak_Locator
  - wget -O magento-sample-data-1.6.1.0.zip http://www.magentocommerce.com/downloads/assets/1.6.1.0/magento-sample-data-1.6.1.0.zip
  - unzip -q magento-sample-data-1.6.1.0.zip
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `magento_travis`;'
  - mysql -uroot magento_travis < magento-sample-data-1.6.1.0/magento_sample_data_for_1.6.1.0.sql
  - php -f install.php -- --license_agreement_accepted yes --locale en_AU --timezone Australia/Melbourne --default_currency AUD --db_host localhost --db_name magento_travis --db_user root --db_pass "" --url http://travis.magento.local/ --skip_url_validation yes --use_rewrites yes --use_secure no --secure_base_url --use_secure_admin no --admin_firstname Andrew --admin_lastname Kett --admin_email admin@example.com --admin_username admin --admin_password password123
  - git clone git@github.com:andrewkett/Ak_LocatorDev.git .modman/Ak_LocatorDev
  - ./modman deploy Ak_LocatorDev
  - rm -rf var/cache/*
script:
  - php shell/indexer.php reindexall #just reindex everything for now until tests are built
  - php shell/locator/installsampledata.php
after_script:
  - curl localhost:9200/locator/search