language: php

env:
  - DB=mysql

php:
  - 5.3

before_script:
  - cp ./src/* ./
  - wget -O modgit https://raw.github.com/jreinke/modgit/master/modgit
  - chmod +x modgit
  - sudo mv modgit /usr/local/bin
  - modgit init
  - modgit clone -t 1.7.0.2 magento https://github.com/andrewkett/magento-mirror.git
  - wget -O magento-sample-data-1.6.1.0.zip http://www.magentocommerce.com/downloads/assets/1.6.1.0/magento-sample-data-1.6.1.0.zip
  - unzip -q magento-sample-data-1.6.1.0.zip
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `magento_travis`;'
  - mysql -uroot magento_travis < magento-sample-data-1.6.1.0/magento_sample_data_for_1.6.1.0.sql
  - php -f install.php -- --license_agreement_accepted yes --locale en_AU --timezone Australia/Melbourne --default_currency AUD --db_host localhost --db_name magento_travis --db_user root --db_pass "" --url http://travis.magento.local/ --skip_url_validation yes --use_rewrites yes --use_secure no --secure_base_url --use_secure_admin no --admin_firstname Andrew --admin_lastname Kett --admin_email admin@example.com --admin_username admin --admin_password password123
  - rm -rf var/cache/*
script:

after_script:
